# Load overlay Brewfile if exists (for company-specific packages)
overlay_brewfile = File.join(__dir__, "overlay", "Brewfile")
if File.exist?(overlay_brewfile)
  eval(File.read(overlay_brewfile))
end

tap "homebrew/autoupdate"
brew "git"
brew "asdf"
brew "aws-sam-cli"
brew "awscli"
brew "direnv"
brew "ffmpeg"
brew "gh"
brew "ghq"
brew "git-filter-repo"
brew "jq"
brew "k9s"
brew "mysql-client@8.0"
brew "peco"
brew "pinentry-mac"
brew "tree"
brew "vim"
brew "yt-dlp"
brew "zsh"
cask "adobe-creative-cloud"
cask "android-studio"
cask "canva"
cask "chatgpt"
cask "claude"
cask "cursor"
cask "deepl"
cask "discord"
cask "discord@ptb"
cask "docker-desktop"
cask "dropbox"
cask "font-migu-1p"
cask "font-noto-sans-cjk"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "notion"
cask "sequel-ace"
cask "session-manager-plugin"
cask "visual-studio-code"
vscode "anthropic.claude-code"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "golang.go"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
