# Load overlay Brewfile if exists (for company-specific packages)
overlay_brewfile = File.join(__dir__, "overlay", "Brewfile")
if File.exist?(overlay_brewfile)
  eval(File.read(overlay_brewfile))
end

tap "dlvhdr/formulae"
tap "homebrew/autoupdate"
brew "aws-sam-cli"
brew "html2markdown"
brew "mise"
brew "mysql-client@8.0"
brew "pinentry-mac"
brew "dlvhdr/formulae/diffnav"
cask "adobe-creative-cloud"
cask "affinity"
cask "android-studio"
cask "canva"
cask "chatgpt"
cask "claude"
cask "cursor"
cask "deepl"
cask "discord"
cask "discord@ptb"
cask "docker-desktop"
cask "dropbox"
cask "font-meslo-for-powerlevel10k"
cask "font-migu-1p"
cask "font-noto-sans-cjk"
cask "font-source-han-code-jp"
cask "font-source-han-sans-vf"
cask "gcloud-cli"
cask "ghostty"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "notion"
cask "obs"
cask "omnidisksweeper"
cask "postman"
cask "sequel-ace"
cask "session-manager-plugin"
cask "snowflake-snowsql"
cask "visual-studio-code"
cask "vlc"
